### ISSUE TITLE
Panic occurred when the example file (under video_upload) ran

### ISSUE THREAD

**Issue by bianer233** [kurrik/twittergo-examples#3]
panic: interface conversion: interface {} is float64, not int64

In the package file models.go, I found this piece codes. 

func (r MediaResponse) MediaId() int64 {
	return r["media_id"].(int64)
}

Anyone else has the same problem?

**Comment by kurrik** [comment]
This is terribly late, but I was able to identify the issue and fix it in https://github.com/kurrik/twittergo/commit/a0a9f31e7d8013ca5620c4a86ee990955f74cf0d
